### ISSUE TITLE
depends_on should trigger service re-creation when the service it depends on has changed

### ISSUE THREAD

**Issue by pdcastro** [balena-io-modules/livepush#58]
If a service dependency is declared with the `depends_on` instruction in `docker-compose.yml` file, so that service A depends on service B, then service A should be restarted if service B is restarted. For example, a change to an environment variable of service B should cause both B and A to be restarted (probably stop A; restart B; (re)start A).

Originally raised as a `balena-cli` issue. Check for full details:
https://github.com/balena-io/balena-cli/issues/1447

**Comment by pdcastro** [comment]
Also created a supervisor issue, as I'm not sure if the implementation would actually be in the livepush module: https://github.com/balena-io/balena-supervisor/issues/1151

**Comment by 20k-ultra** [comment]
I think if we do this it would just from the Supervisor so closing in favor of discussing in https://github.com/balena-os/balena-supervisor/issues/1151
